[project]
name = "cat-polars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2024.11.0",
    "ipykernel>=6.30.0",
    "pandas>=2.3.1",
    "polars[graph,pandas,plot]>=1.31.0",
]
